### ISSUE TITLE
Cublas Error - CUBLAS_STATUS_EXECUTION_FAILED with interact scipt

### ISSUE THREAD

**Issue by bakszero** [PaddlePaddle/Knover#11]
Hi, while running the interactive script for both the 24L and 32L models, I faced the following CUBLAS error.
I'm running the script on Ubuntu 18.04 with 4 Tesla T4 16GB GPUs on GCP. 

```shell
W0715 13:57:42.359799 16069 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.0
W0715 13:57:42.362675 16069 device_context.cc:260] device: 0, cuDNN Version: 8.0.
Load pretraining parameters from ./24L/Plato.
Enter [EXIT] to quit the interaction, [NEXT] to start a new conversation.
[Human]: hey
/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "./interaction.py", line 83, in <module>
    interact(args)
  File "./interaction.py", line 72, in interact
    pred = task.infer_step(model, data)[0]
  File "/mnt/disks/disk-huge/bakht/Knover/tasks/task_base.py", line 46, in infer_step
    predictions = model.infer_step(inputs)
  File "/mnt/disks/disk-huge/bakht/Knover/models/plato.py", line 243, in infer_step
    return super(Plato, self).infer_step(inputs)
  File "/mnt/disks/disk-huge/bakht/Knover/models/unified_transformer.py", line 506, in infer_step
    return self._run_generation(inputs)
  File "/mnt/disks/disk-huge/bakht/Knover/models/unified_transformer.py", line 462, in _run_generation
    return_numpy=False)
  File "/mnt/disks/disk-huge/bakht/Knover/models/model_base.py", line 258, in _execute
    fetch_vars = self.exe.run(program, feed, fetch_list, return_numpy=return_numpy)
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/bakht/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6414, in matmul
    attrs=attrs)
  File "/mnt/disks/disk-huge/bakht/Knover/models/plato.py", line 194, in forward
    latent_emb = layers.matmul(x=weights, y=latent_embeddings, transpose_y=True)
  File "/mnt/disks/disk-huge/bakht/Knover/models/model_base.py", line 90, in _build_programs
    outputs = self.forward(inputs, is_infer=True)
  File "/mnt/disks/disk-huge/bakht/Knover/models/model_base.py", line 74, in __init__
    self._build_programs()
  File "/mnt/disks/disk-huge/bakht/Knover/models/unified_transformer.py", line 98, in __init__
    super(UnifiedTransformer, self).__init__(args, place)
  File "/mnt/disks/disk-huge/bakht/Knover/models/plato.py", line 50, in __init__
    super(Plato, self).__init__(args, place)
  File "/mnt/disks/disk-huge/bakht/Knover/models/__init__.py", line 49, in create_model
    return MODEL_REGISTRY[args.model](args, place)
  File "./interaction.py", line 54, in interact
    model = models.create_model(args, place)
  File "./interaction.py", line 83, in <module>
    interact(args)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]
```

**Comment by sserdoubleh** [comment]
Can you output the version of your used paddlepadle?

**Comment by bakszero** [comment]
> What is the version of your used paddlepadle?
It is 1.8.2.post107

**Comment by sserdoubleh** [comment]
How about using CUDA==1.0.0 and CUDNN==7.6？

**Comment by sserdoubleh** [comment]
You can reopen the issue if the problem still exists.
