### ISSUE TITLE
运行train.py时出现以下错误

### ISSUE THREAD

**Issue by chikin-lau** [PaddlePaddle/Knover#129]
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEARE
ST or Dither.NONE instead.
  'nearest': Image.NEAREST,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILI
NEAR instead.
  'bilinear': Image.BILINEAR,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUB
IC instead.
  'bicubic': Image.BICUBIC,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX inste
ad.
  'box': Image.BOX,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZ
OS instead.
  'lanczos': Image.LANCZOS,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMI
NG instead.
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    import knover.models as models
ModuleNotFoundError: No module named 'knover'

没有找到模块knover，但是打开对应文件第29行，编辑器在导入knover时并没有提示有错？

**Comment by chikin-lau** [comment]
在运行lic2022的baseline时报错
输入：sh ./scripts/local/job.sh  ./projects/lic2022/conf/query_train.conf
报错：
+ [[ 1 != 1 ]]
+ job_conf=./projects/lic2022/conf/query_train.conf
+ source ./projects/lic2022/conf/query_train.conf
++ job_script=./scripts/distributed/train.sh
++ model=UnifiedTransformer
++ task=DialogGeneration
++ vocab_path=./projects/lic2022/conf/vocab.txt
++ spm_model_file=./projects/lic2022/conf/spm.model
++ train_file=./projects/lic2022/preprocess_data/train_query.txt
++ valid_file=./projects/lic2022/preprocess_data/dev_query.txt
++ data_format=raw
++ file_format=file
++ config_path=./projects/lic2022/conf/query.json
++ init_params=./projects/lic2022/model_zoo/12L.pretrain
++ in_tokens=true
++ batch_size=8192
++ lr=1e-5
++ warmup_steps=400
++ weight_decay=0.01
++ train_args='--max_src_len 384 --max_tgt_len 128 --max_seq_len 512'
++ num_epochs=10
++ log_steps=10
++ validation_steps=200
++ save_steps=200
++ log_dir=./projects/lic2022/train_query/log
++ save_path=./projects/lic2022/train_query/output
+ [[ ./projects/lic2022/train_query/log != '' ]]
+ rm ./projects/lic2022/train_query/log/workerlog.0
++ dirname ./scripts/local/job.sh
+ export PYTHONPATH=./scripts/local/../..:
+ PYTHONPATH=./scripts/local/../..:
+ ./scripts/distributed/train.sh ./projects/lic2022/conf/query_train.conf
+ [[ 1 == 1 ]]
+ job_conf=./projects/lic2022/conf/query_train.conf
+ source ./projects/lic2022/conf/query_train.conf
++ job_script=./scripts/distributed/train.sh
++ model=UnifiedTransformer
++ task=DialogGeneration
++ vocab_path=./projects/lic2022/conf/vocab.txt
++ spm_model_file=./projects/lic2022/conf/spm.model
++ train_file=./projects/lic2022/preprocess_data/train_query.txt
++ valid_file=./projects/lic2022/preprocess_data/dev_query.txt
++ data_format=raw
++ file_format=file
++ config_path=./projects/lic2022/conf/query.json
++ init_params=./projects/lic2022/model_zoo/12L.pretrain
++ in_tokens=true
++ batch_size=8192
++ lr=1e-5
++ warmup_steps=400
++ weight_decay=0.01
++ train_args='--max_src_len 384 --max_tgt_len 128 --max_seq_len 512'
++ num_epochs=10
++ log_steps=10
++ validation_steps=200
++ save_steps=200
++ log_dir=./projects/lic2022/train_query/log
++ save_path=./projects/lic2022/train_query/output
+ export FLAGS_sync_nccl_allreduce=1
+ FLAGS_sync_nccl_allreduce=1
+ export FLAGS_fuse_parameter_memory_size=64
+ FLAGS_fuse_parameter_memory_size=64
+ mkdir -p ./projects/lic2022/train_query/output
+ [[ ./projects/lic2022/train_query/log != '' ]]
+ mkdir -p ./projects/lic2022/train_query/log
+ distributed_args=' --log_dir ./projects/lic2022/train_query/log'
+ fleetrun --log_dir ./projects/lic2022/train_query/log ./knover/scripts/train.py --is_distributed true --model UnifiedTransformer --task DialogGeneration --vocab_path ./projects/lic2022/conf/vocab.txt --spm_
model_file ./projects/lic2022/conf/spm.model --init_pretraining_params ./projects/lic2022/model_zoo/12L.pretrain --init_checkpoint '' --train_file ./projects/lic2022/preprocess_data/train_query.txt --valid_fi
le ./projects/lic2022/preprocess_data/dev_query.txt --data_format raw --file_format file --config_path ./projects/lic2022/conf/query.json --max_src_len 384 --max_tgt_len 128 --max_seq_len 512 --in_tokens true
 --batch_size 8192 --learning_rate 1e-5 --warmup_steps 400 --weight_decay 0.01 --use_amp true --use_recompute false --use_sharding false --num_epochs 10 --log_steps 10 --validation_steps 200 --save_steps 200
--save_path ./projects/lic2022/train_query/output --random_seed 11
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEARE
ST or Dither.NONE instead.
  'nearest': Image.NEAREST,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILI
NEAR instead.
  'bilinear': Image.BILINEAR,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUB
IC instead.
  'bicubic': Image.BICUBIC,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX inste
ad.
  'box': Image.BOX,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZ
OS instead.
  'lanczos': Image.LANCZOS,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMI
NG instead.
  'hamming': Image.HAMMING
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: None
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: ./projects/lic2022/train_query/log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: ./knover/scripts/train.py
training_script_args: ['--is_distributed', 'true', '--model', 'UnifiedTransformer', '--task', 'DialogGeneration', '--vocab_path', './projects/lic2022/conf/vocab.txt', '--spm_model_file', './projects/lic2022/c
onf/spm.model', '--init_pretraining_params', './projects/lic2022/model_zoo/12L.pretrain', '--init_checkpoint', '', '--train_file', './projects/lic2022/preprocess_data/train_query.txt', '--valid_file', './proj
ects/lic2022/preprocess_data/dev_query.txt', '--data_format', 'raw', '--file_format', 'file', '--config_path', './projects/lic2022/conf/query.json', '--max_src_len', '384', '--max_tgt_len', '128', '--max_seq_
len', '512', '--in_tokens', 'true', '--batch_size', '8192', '--learning_rate', '1e-5', '--warmup_steps', '400', '--weight_decay', '0.01', '--use_amp', 'true', '--use_recompute', 'false', '--use_sharding', 'fa
lse', '--num_epochs', '10', '--log_steps', '10', '--validation_steps', '200', '--save_steps', '200', '--save_path', './projects/lic2022/train_query/output', '--random_seed', '11']
worker_num: None
workers:
------------------------------------------------
WARNING 2022-04-17 18:57:51,906 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-04-17 18:57:51,922 launch_utils.py:528] Local start 1 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:57773               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:57773               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-04-17 18:57:51,922 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in ./projects/lic2022/train_query/log/endpoints.log, and detail running logs maybe found in ./projects/li
c2022/train_query/log/workerlog.0
命令语法不正确。
launch proc_id:2092 idx:0
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEARE
ST or Dither.NONE instead.
  'nearest': Image.NEAREST,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILI
NEAR instead.
  'bilinear': Image.BILINEAR,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUB
IC instead.
  'bicubic': Image.BICUBIC,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX inste
ad.
  'box': Image.BOX,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZ
OS instead.
  'lanczos': Image.LANCZOS,
E:\software\Anaconda3\envs\Knover\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMI
NG instead.
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "./knover/scripts/train.py", line 29, in <module>
    import knover.models as models
ModuleNotFoundError: No module named 'knover'
INFO 2022-04-17 18:57:58,022 launch_utils.py:341] terminate all the procs
ERROR 2022-04-17 18:57:58,022 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-04-17 18:58:01,022 launch_utils.py:341] terminate all the procs
INFO 2022-04-17 18:58:01,022 launch.py:311] Local processes completed.
+ exit_code=0
+ exit 0

**Comment by chikin-lau** [comment]
在PythonConsole里输入import knover.models as models也没有报错

**Comment by chikin-lau** [comment]
已解决
原来是我忘了运行这个命令：
pip3 install -e .
