### ISSUE TITLE
use_role? missing role_type_size parameter？

### ISSUE THREAD

**Issue by shanekong** [PaddlePaddle/Knover#145]
when training UnifiedTransformer model, if set use_role=True, it will raise following exception; 

Traceback (most recent call last):
  File "C:\Users\\Miniconda3\envs\python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\\Miniconda3\envs\python37\lib\site-packages\paddle\fluid\framework.py", line 6854, in program_guard
    yield
  File "e:\chatbot\git_code\knover\knover\core\model.py", line 228, in _build_programs
    outputs = self.forward(inputs)
  File "e:\chatbot\git_code\knover\knover\models\unified_transformer.py", line 435, in forward
    gather_idx=inputs.get("parent_idx", None)
  File "e:\chatbot\git_code\knover\knover\models\unified_transformer.py", line 261, in _generation_network
    name=name)
  File "e:\chatbot\git_code\knover\knover\models\unified_transformer.py", line 154, in _gen_input
    name=name + self.role_emb_name, initializer=self.param_initializer))
  File "C:\Users\\Miniconda3\envs\python37\lib\site-packages\paddle\fluid\layers\nn.py", line 509, in embedding
    attr=helper.param_attr, shape=size, dtype=dtype, is_bias=False)
  File "C:\Users\\Miniconda3\envs\python37\lib\site-packages\paddle\fluid\layer_helper_base.py", line 319, in create_parameter
    assert size > 0, (
TypeError: '>' not supported between instances of 'NoneType' and 'int'
python-BaseException

**Comment by sserdoubleh** [comment]
Please add role_type_size in your model config (the json format config).

**Comment by sserdoubleh** [comment]
Such as: https://github.com/PaddlePaddle/Knover/blob/38c699777add43aaf7cda4a78e91c8bfd638b240/projects/DSTC9-Track1/32L.json#L16

**Comment by shanekong** [comment]
thanks for your reply.
