### ISSUE TITLE
sh ./scripts/24L_plato_training.sh报错，请帮忙看看是什么原因

### ISSUE THREAD

**Issue by mali19064** [PaddlePaddle/Knover#15]
我装的paddle版本是1.8.2.post107 paddlehub版本是1.5.3，错误信息如下：
ERROR 2020-07-21 14:44:20,106 utils.py:422] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
Traceback (most recent call last):
  File "/home/li.ma/anaconda3/lib/python3.7/site-packages/paddle/distributed/utils.py", line 406, in watch_local_trainers
    terminate_local_procs(procs)
  File "/home/li.ma/anaconda3/lib/python3.7/site-packages/paddle/distributed/utils.py", line 257, in terminate_local_procs
    p.proc.join(timeout=1)
AttributeError: 'Popen' object has no attribute 'join'

**Comment by sserdoubleh** [comment]
可以输出下log/workerlog.0的输出日志吗？

**Comment by mali19064** [comment]
已解决，是paddlepaddle有bug，根据https://github.com/PaddlePaddle/Paddle/pull/24767/files做了修复

**Comment by sserdoubleh** [comment]
好的，有问题再重新开这个 issue 吧
