### ISSUE TITLE
DSTC10-Track2/task2 inference code: Error while running the command 'bash ./submission_0_infer.sh'

### ISSUE THREAD

**Issue by JH-debug** [PaddlePaddle/Knover#152]
When running DSTC10-Track2/task2 (Knowledge-grounded Dialogue Modeling), I got error message like this. 
Please help me to fix the following error.

the error message:
```
Load pretraining parameters from /home/Knover/projects/DSTC10-Track2/task2/models/SOP-32L-Detection
Traceback (most recent call last):
  File "/home/Knover/knover/data/dialog_reader.py", line 578, in __wrapper__
    for batch in batch_reader():
  File "/home/Knover/knover/data/dialog_reader.py", line 517, in __wrapper__
    for batch in batch_reader():
  File "/home/Knover/knover/data/dialog_reader.py", line 432, in __wrapper__
    for record in reader():
  File "/home/Knover/knover/data/dialog_reader.py", line 369, in __wrapper__
    yield from self._read_numerical_file(fp, phase, is_infer)
TypeError: _read_numerical_file() takes from 2 to 3 positional arguments but 4 were given
WARNING:root:Your reader has raised an exception!
Traceback (most recent call last):
Exception in thread   File "./knover/scripts/infer.py", line 145, in <module>
Thread-1:
Traceback (most recent call last):
      File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
infer(args)
    for step, data in enumerate(infer_generator(), 1):
  File "/home/Knover/myenv/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1392, in __next__
        return self._reader.read_next()self.run()

SystemError:   File "/usr/lib/python3.8/threading.py", line 870, in run
(Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```

Thank you for taking the time to review this.

**Comment by sserdoubleh** [comment]
How about the git log id? Are you using the latest develop branch?
https://github.com/PaddlePaddle/Knover/blob/31a659a9b1bbd5b7a1f911ed34c964d77f6c9cc4/knover/data/dialog_reader.py#L346
_read_numerical_file take 4~5 positional arguments here.

**Comment by JH-debug** [comment]
Yes, I used the latest develop branch. I don't know why I got the error. Anyway, Thank you for your fast reply.

**Comment by sserdoubleh** [comment]
I find the bug, i will fix it soon.

**Comment by sserdoubleh** [comment]
You can try the latest develop branch now~
https://github.com/PaddlePaddle/Knover/pull/154

**Comment by JH-debug** [comment]
Wow. Thank you so much!
