### ISSUE TITLE
Exception: 'feed_targets' does not have label_pos variable

### ISSUE THREAD

**Issue by aszxnm** [PaddlePaddle/Knover#44]
Traceback (most recent call last):
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/perfectworld/gx/Knover/knover/scripts/interact.py", line 83, in <module>
    interact(args)
  File "/home/perfectworld/gx/Knover/knover/scripts/interact.py", line 70, in interact
    pred = task.infer_step(model, data)[0]
  File "/home/perfectworld/gx/Knover/knover/core/task.py", line 46, in infer_step
    outputs = self._post_process_infer_output(predictions)
  File "/home/perfectworld/gx/Knover/knover/tasks/dialog_generation.py", line 162, in _post_process_infer_output
    return self._post_process_generation_output(predictions)
  File "/home/perfectworld/gx/Knover/knover/tasks/dialog_generation.py", line 91, in _post_process_generation_output
    get_nsp_score_batch(self.nsp_predictor, predictions)
  File "/home/perfectworld/gx/Knover/knover/tasks/dialog_generation.py", line 404, in get_nsp_score_batch
    outputs = nsp_predictor(data)
  File "/home/perfectworld/gx/Knover/knover/utils/inference_utils.py", line 44, in __predict__
    return_numpy=True)
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1238, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1313, in _run_program
    fetch_var_name=fetch_var_name)
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/paddle/fluid/executor.py", line 624, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "/home/perfectworld/anaconda3/envs/dialogue/lib/python3.7/site-packages/paddle/fluid/executor.py", line 280, in has_feed_operators
    format(feed_target_name))
Exception: 'feed_targets' does not have label_pos variable

Dear sir, do you meet this problem? How to fix it?

**Comment by sserdoubleh** [comment]
Are you using the checkpoint downloaded from PLATO-2 project？
Maybe you need to remove the old-format "`__model__`": in `${MODEL_SIZE}/NSP/__model__`
And then re-run the interaction (it will generate new-format "`__model__`")

**Comment by aszxnm** [comment]
> Are you using the checkpoint downloaded from PLATO-2 project？
> Maybe you need to remove the old-format "`__model__`": in `${MODEL_SIZE}/NSP/__model__`
> And then re-run the interaction (it will generate new-format "`__model__`")

Thank you very much. It runs~
